/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2
 */


public class DATA extends javax.swing.JFrame {
    int num_ticket ;
    int x;
    

    /**
     * Creates new form DATA
     */
    public DATA() {
        initComponents();
        createEssentialDate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboxDestiny = new javax.swing.JComboBox<>();
        cboxDate = new javax.swing.JComboBox<>();
        TxtLocation = new javax.swing.JTextField();
        TxtName = new javax.swing.JTextField();
        cboxClass = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtMail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtPhone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtSeatNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cboxSeatCat = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        LabelMail = new javax.swing.JLabel();
        LabelPhone = new javax.swing.JLabel();
        LabelLocation = new javax.swing.JLabel();
        LabelID = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        LabelDestiny = new javax.swing.JLabel();
        LabelClass = new javax.swing.JLabel();
        LabelDate = new javax.swing.JLabel();
        LabelSeatNo = new javax.swing.JLabel();
        LabelSeatCat = new javax.swing.JLabel();
        LabelCost = new javax.swing.JLabel();
        LabelGate = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BOOKING", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Destiny");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 128, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Seat Category");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 156, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 156, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Location");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 156, 21));

        cboxDestiny.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "America", "NewZealand", "Germany", "France", "Brazil" }));
        cboxDestiny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxDestinyActionPerformed(evt);
            }
        });
        jPanel2.add(cboxDestiny, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 450, 30));

        cboxDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5/1/2021", "6/1/2021", "7/1/2021", "8/1/2021", "9/1/2021", "10/1/2021", "11/1/2021", "12/1/2021", "13/1/2021" }));
        cboxDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxDateActionPerformed(evt);
            }
        });
        jPanel2.add(cboxDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 450, 30));

        TxtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLocationActionPerformed(evt);
            }
        });
        jPanel2.add(TxtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 450, 30));
        jPanel2.add(TxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 450, 30));

        cboxClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First", "Business", "Economy", " " }));
        cboxClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxClassActionPerformed(evt);
            }
        });
        jPanel2.add(cboxClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 450, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Flight class");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 156, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Passport ID");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 156, -1));

        TxtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIDActionPerformed(evt);
            }
        });
        jPanel2.add(TxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 450, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("E-Mail");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 156, -1));
        jPanel2.add(TxtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 450, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Number");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 156, 21));

        TxtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPhoneActionPerformed(evt);
            }
        });
        jPanel2.add(TxtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 450, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText(" Date");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 342, 160, 20));

        TxtSeatNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSeatNoActionPerformed(evt);
            }
        });
        jPanel2.add(TxtSeatNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 450, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Seat No.");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 156, -1));

        cboxSeatCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "( A )", "( B )", "( C )", " ", " ", " " }));
        jPanel2.add(cboxSeatCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 450, 30));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BOOKING", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        LabelMail.setBackground(new java.awt.Color(255, 153, 204));
        LabelMail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelMail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        LabelPhone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        LabelLocation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelLocation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        LabelID.setBackground(new java.awt.Color(255, 153, 204));
        LabelID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        labelName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        LabelDestiny.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelDestiny.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        LabelClass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelClass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        LabelDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        LabelSeatNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelSeatNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        LabelSeatCat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelSeatCat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        LabelCost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelCost.setText("Total Cost");
        LabelCost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        LabelGate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelGate.setText("Gate");
        LabelGate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelMail, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDestiny, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelClass, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSeatNo, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSeatCat, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCost, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelGate, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelMail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(LabelDestiny, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelSeatNo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelSeatCat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelClass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(LabelGate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelCost, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Tickets");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Tickets price");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(210, 210, 210)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(660, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(449, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        labelName.setText(TxtName.getText());
        LabelMail.setText(TxtMail.getText());
        LabelID.setText(TxtID.getText());
        LabelPhone.setText(TxtPhone.getText());
        LabelLocation.setText(TxtLocation.getText());
        LabelDestiny.setText(cboxDestiny.getSelectedItem().toString());   
        LabelDate.setText(cboxDate.getSelectedItem().toString());
       
        LabelSeatNo.setText(TxtSeatNo.getText());
        LabelSeatCat.setText(cboxSeatCat.getSelectedItem().toString());
        LabelClass.setText(cboxClass.getSelectedItem().toString());
        
        
        String pName = TxtName.getText();
        String destinationCountry = cboxDestiny.getSelectedItem().toString();
        
        String pNo = TxtID.getText();
        int row_no = int.parse ( TxtSeatNo.getText());
        char cat = cboxSeatCat.getSelectedItem().toString()[0];
        FlightSeat fs = makeTicket(destination, flight,destinationCountry ,row_no,  cat, pName, pNo) ;
        
                
        
        
        
        
       

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private FlightDestination[] destination;// = new FlightDestination[5];
    private Flight[] flight;// = new Flight[10];
    private Airoplane[] airplane;//  = new Airoplane[2];
    
    private void  createEssentialDate() {
        destination = new FlightDestination[5];
        destination[0] = new FlightDestination("America",50000,40000,30000);
        destination[1] = new FlightDestination("NewZealand",40000,30000,20000);
        destination[2] = new FlightDestination("Germany",20000,15000,10000);
        destination[3] = new FlightDestination("France",25000,15000,17000);
        destination[4] = new FlightDestination("Brazil",15000,20000,10000);
        
       // System.out.println(destination[4].getName() + "\n" + destination[4].getBusinessPrice());
        
        
        airplane  = new Airoplane[2];
        airplane[0] = new Airoplane("Boing",4,6,8,10,5,50);
        airplane[1] = new Airoplane("Airbus",6,8,10,15,10,60);
        
        //System.out.println("Air plan Date:");
        
        /*Seat[] seats = airplane[1].getPlaneSeat();
        int count = seats.length;
        for(int i=0; i < count ; i++) {
            Seat s = seats[i];
        System.out.println( i + ": " +  s.seatId());
        }*/
        
        //System.out.println("Flight Dat:");
        
        flight = new Flight[10];
        flight[0] = new Flight(airplane[0],"Cairo",destination[0],"1/5/2020","19.30","12.00");
        flight[1] = new Flight(airplane[0],"Cairo",destination[1],"2/5/2020","19.30","12.00");
        flight[2] = new Flight(airplane[0],"Cairo",destination[3],"3/5/2020","19.30","12.00");
        flight[3] = new Flight(airplane[0],"Cairo",destination[2],"6/5/2020","19.30","12.00");
        flight[4] = new Flight(airplane[0],"Cairo",destination[4],"5/5/2020","19.30","12.00");
        flight[5] = new Flight(airplane[1],"Cairo",destination[0],"5/5/2020","19.30","12.00");
        flight[6] = new Flight(airplane[1],"Cairo",destination[4],"7/5/2020","19.30","12.00");
        flight[7] = new Flight(airplane[1],"Cairo",destination[2],"1/5/2020","19.30","12.00");
        flight[8] = new Flight(airplane[1],"Cairo",destination[1],"10/5/2020","19.30","12.00");
        flight[9] = new Flight(airplane[1],"Cairo",destination[3],"11/5/2020","19.30","12.00");

    }
    private static FlightSeat makeTicket(FlightDestination[] destination,Flight[] flight , String destinationCountry, int row_no, char cat, String pName, String pNo) {
        Flight userFlight = null;
        for(int i=0 ; i < flight.length; i++) {
            if(flight[i].getDetination().equals(destinationCountry)) {
                userFlight = flight[i];
            }
        }
        if(userFlight == null)
            return null;
        
        
        try {
        Passenger p= new Passenger(pName,pNo);
        
        String id = String.format("%d%c", row_no, cat);
        FlightSeat fs = userFlight.getseatbyID(id);
        if(fs == null)
            return null;
        userFlight.setTicket(p, fs);
        fs = userFlight.getseatbyID(id);
        //System.out.println(   fs.seatId() + " : " + fs.getStatus() + " : " + fs.getPrice() );
        //System.out.println(userFlight.getAvailableSeatCount()+":" + userFlight.getTotalSeatsCount());
        
        }catch (IllegalArgumentException e ) {
            System.out.println("ERROR ALLOCATION SEAT: " + e.getMessage());
        }
        return fs;
        //fs = userFlight.getseatbyID(id);
        
    }
    
    private void cboxClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxClassActionPerformed

    private void TxtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLocationActionPerformed

    private void cboxDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxDateActionPerformed

    private void cboxDestinyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxDestinyActionPerformed

        // TODO add your handling code here:
       // cboxDestiny.
    }//GEN-LAST:event_cboxDestinyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TxtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDActionPerformed

    private void TxtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPhoneActionPerformed

    private void TxtSeatNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSeatNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSeatNoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DATA().setVisible(true);
            }
        });
    }
   
    private void temp() {
        FlightDestination [] destination = new FlightDestination[5];
        destination[0] = new FlightDestination("America",50000,40000,30000);
        destination[1] = new FlightDestination("NewZealand",40000,30000,20000);
        destination[2] = new FlightDestination("Germany",20000,15000,10000);
        destination[3] = new FlightDestination("France",25000,15000,17000);
        destination[4] = new FlightDestination("Brazil",15000,20000,10000);
        
        Airoplane [] airplane  = new Airoplane[2];
        airplane[0] = new Airoplane("Boing",4,6,8,10,5,50);
        airplane[1] = new Airoplane("Airbus",6,8,10,15,10,60);
        
        Flight [] flight = new Flight[10];
        flight[0] = new Flight(airplane[0],"Cairo",destination[0],"1/5/2020","19.30","12.00");
        flight[1] = new Flight(airplane[0],"Cairo",destination[1],"2/5/2020","19.30","12.00");
        flight[2] = new Flight(airplane[0],"Cairo",destination[3],"3/5/2020","19.30","12.00");
        flight[3] = new Flight(airplane[0],"Cairo",destination[2],"6/5/2020","19.30","12.00");
        flight[4] = new Flight(airplane[0],"Cairo",destination[4],"5/5/2020","19.30","12.00");
        flight[5] = new Flight(airplane[1],"Cairo",destination[0],"5/5/2020","19.30","12.00");
        flight[6] = new Flight(airplane[1],"Cairo",destination[4],"7/5/2020","19.30","12.00");
        flight[7] = new Flight(airplane[1],"Cairo",destination[2],"1/5/2020","19.30","12.00");
        flight[8] = new Flight(airplane[1],"Cairo",destination[1],"10/5/2020","19.30","12.00");
        flight[9] = new Flight(airplane[1],"Cairo",destination[3],"11/5/2020","19.30","12.00");

       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelClass;
    private javax.swing.JLabel LabelCost;
    private javax.swing.JLabel LabelDate;
    private javax.swing.JLabel LabelDestiny;
    private javax.swing.JLabel LabelGate;
    private javax.swing.JLabel LabelID;
    private javax.swing.JLabel LabelLocation;
    private javax.swing.JLabel LabelMail;
    private javax.swing.JLabel LabelPhone;
    private javax.swing.JLabel LabelSeatCat;
    private javax.swing.JLabel LabelSeatNo;
    public javax.swing.JTextField TxtID;
    public javax.swing.JTextField TxtLocation;
    public javax.swing.JTextField TxtMail;
    public javax.swing.JTextField TxtName;
    public javax.swing.JTextField TxtPhone;
    public javax.swing.JTextField TxtSeatNo;
    public javax.swing.JComboBox<String> cboxClass;
    public javax.swing.JComboBox<String> cboxDate;
    public javax.swing.JComboBox<String> cboxDestiny;
    private javax.swing.JComboBox<String> cboxSeatCat;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelName;
    // End of variables declaration//GEN-END:variables
}
